version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: linkedin_ai_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  dev:
    image: elixir:1.15-alpine
    working_dir: /app
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=ecto://postgres:postgres@db:5432/linkedin_ai_dev
      - SECRET_KEY_BASE=your_secret_key_base_here_for_development
      - PHX_HOST=localhost
      - PORT=4000
      - PHX_SERVER=true
      - MIX_ENV=dev
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
      - elixir_deps:/app/deps
      - elixir_build:/app/_build
      - node_modules:/app/assets/node_modules
    command: >
      sh -c "
        apk add --no-cache build-base npm git python3 inotify-tools &&
        mix local.hex --force &&
        mix local.rebar --force &&
        mix deps.get &&
        npm --prefix ./assets install &&
        mix ecto.setup &&
        mix phx.server
      "

  # Development services
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    environment:
      - MH_STORAGE=maildir
      - MH_MAILDIR_PATH=/maildir
    volumes:
      - mailhog_data:/maildir

volumes:
  postgres_data:
  redis_data:
  mailhog_data:
  elixir_deps:
  elixir_build:
  node_modules: